build-job:
  stage: build
  script:
    - echo "Hello, try new feature!, $GITLAB_USER_LOGIN!"

test-job1:
  stage: test
  script:
    - echo "This job tests something"
    - sleep 20
#  only:
#      - merge_requests

test-job2:
  stage: test
#  only:
#    - merge_requests
  script:
    - echo "This job tests something, but takes more time than test-job1."
    - echo "After the echo commands complete, it runs the sleep command for 20 seconds"
    - echo "which simulates a test that runs 20 seconds longer than test-job1"
    - mvn test
    - sleep 4
  tags:
    - docker
    - jdk17
    - "3.8.5"
    - mvn

#deploy-prod:
#  stage: deploy
#  script:
#    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
#  environment: production